database_url = "sqlite:state.db"
discord_token = "TyPlB7gsd1wiLmkiesuZ.EJI9nvRlmTFMO8TI6QC.AcWrrm7ysVvcV2Jdc9wE"
github_app_id = 123456
github_private_key = "./path/to/private-key.pem"

[mapping."owner/repository"]
target = { id = 898362774930728025, type = "Guild" }
roles = [8983627711012531191]

[mapping."owner/otherrepository"]
target = { id = 767279711012531191, type = "Channel" }
roles = [767279730728025]
